return {
    MC_POST_SLOT_INIT = 0,
    MC_POST_SLOT_UPDATE = 1,
    MC_POST_SLOT_PRIZE = 2,
    MC_PRE_SLOT_COLLISION = 3,

    MC_POST_PLAYER_COLLECTIBLE_ADDED = 4,
    MC_POST_PLAYER_COLLECTIBLE_REMOVED = 5,

    MC_POST_PLAYER_GULPED_TRINKET_ADDED = 6,
    MC_POST_PLAYER_GULPED_TRINKET_REMOVED = 7,

    MC_POST_GRID_ENTITY_UPDATE = 8,
}